#!/bin/bash

# Display help section
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    echo "Usage: ./dump_analyser.sh <core_file>"
    echo "Example: ./dump_analyser.sh core.10896"
    echo "  -h, --help   Display this help message and exit"
    exit 0
fi

# ============================================================================
# Function Definitions (must be defined before use)
# ============================================================================

# Function to get terminal width (default to 80 if not available)
function get_terminal_width() {
  local width=$(tput cols 2>/dev/null || echo "80")
  echo "$width"
}

# Function to print a separator line using terminal width
function print_separator() {
  local char="${1:-"-"}"
  local width=$(get_terminal_width)
  printf "%*s\n" "$width" "" | tr " " "$char"
}

# Function to print a boxed header using terminal width
function print_boxed_header() {
  local text="$1"
  local width=$(get_terminal_width)
  local padding=$((width - 4))
  local line=$(printf "%*s" "$width" "" | tr " " "*")
  echo "$line"
  printf "* %-${padding}s *\n" "$text"
  echo "$line"
  echo
}

# Function to center text in terminal width
function print_centered() {
  local text="$1"
  local width=$(get_terminal_width)
  local text_len=${#text}
  # If text is longer than width, just print it (no centering)
  if [ $text_len -ge $width ]; then
    echo "$text"
  else
    local padding=$(( (width - text_len) / 2 ))
    printf "%*s%s\n" "$padding" "" "$text"
  fi
}

# Function to show blinkdots for various steps in progress when needed in the script.
# Note: Don't use this when a progress bar is already running (like curl -#)
function blinkdots() {
  local pid=$1
  local delay=0.5
  while kill -0 $pid 2>/dev/null; do
    printf "."
    sleep $delay
    printf "."
    sleep $delay
    printf "."
    sleep $delay
    printf "\b\b\b   \b\b\b"
    sleep $delay
  done
  printf "\n"
}

# Function to display error message and exit
function error_exit() {
  echo "❌ $1" >&2
  exit 1
}

# ============================================================================
# Main Script
# ============================================================================

# Add a pretty welcome message using terminal width
width=$(get_terminal_width)
line=$(printf "%*s" "$width" "" | tr " " "*")
echo "$line"
print_centered "Welcome to Core Dump Analyzer"
print_centered "I am just a tiny tool to analyse the core file to ease the life of YB team"
print_centered "⚙️  For any issue please use #yb-support-tools Slack Channel"
print_centered "♨️  Feel free to contribute: https://github.com/ag26jan/dump_analyser_project-scripts"
print_centered "✍️  Authored By: Ashok Gangwar (ag26jan[at]gmail[dot]com)"
echo "$line"
echo

# Enable tab-completion for file names
if [ $# -eq 0 ]; then
  read -e -p "Enter the Core dump file name: " file_name
else
  file_name=$1
fi

# Check if the Core file exists

if [ ! -f "$file_name" ]; then
  error_exit " The file '$file_name' does not exist."
fi

# Separator
print_separator

# Check if the Core file is a valid core dump

file_type=$(file "$file_name")
if echo "$file_type" | grep -q "core file"; then
  echo "🎉 Great! The core dump file provided is a valid core dump, proceeding with analysis."
  echo "👉 NOTE: If the core file is huge, this can take some time. Please be patient and have a sip of 🍺"
else
  error_exit "The Core dump file is NOT an ELF core dump. Please provide a valid core dump file. Make sure the file IS NOT compressed - if so, please extract it and then try again!"
fi

# Identify process type from core dump using GDB (PRIMARY GOAL)
# We only need to identify the process type - we'll find the binary in downloaded software later
# This approach is more robust and handles corrupted GDB output better
yb_executable_process=""

# Check if GDB is available
if ! command -v gdb >/dev/null 2>&1; then
    error_exit " GDB is required but not found. Please install GDB to analyze core dumps."
fi

# Use GDB's info proc cmdline to identify the process
# Filter out "New LWP" messages to keep output clean
echo "🔍 Identifying process type from core dump..."
gdb_cmdline_output=$(gdb -batch -c "$file_name" -ex "info proc cmdline" 2>/dev/null | grep -v "^\[New LWP" | grep -v "^\[Current thread")

if ! echo "$gdb_cmdline_output" | grep -q "Core was generated by"; then
    error_exit " Could not extract executable information from core dump using GDB. The core file may be corrupted or invalid."
fi

core_generated_line=$(echo "$gdb_cmdline_output" | grep "Core was generated by")

# PRIMARY GOAL: Identify process type from GDB output
# This works even with corrupted/truncated output
if echo "$core_generated_line" | grep -qiE '(odyssey|/bin/odyssey)'; then
    yb_executable_process="odyssey"
elif echo "$core_generated_line" | grep -qiE '(yb-tserver|/bin/yb-tserver)'; then
    yb_executable_process="yb-tserver"
elif echo "$core_generated_line" | grep -qiE '(yb-master|/bin/yb-master)'; then
    yb_executable_process="yb-master"
elif echo "$core_generated_line" | grep -qiE '/postgres/bin/postgres'; then
    yb_executable_process="postgres"
elif echo "$core_generated_line" | grep -qiE '(postgres|/bin/postgres)'; then
    # Check if it's postgres or odyssey - odyssey can be misidentified as postgres
    # If path shows /bin/postgres (not /postgres/bin/), it's likely odyssey
    if echo "$core_generated_line" | grep -qE '/bin/postgres' && ! echo "$core_generated_line" | grep -qE '/postgres/bin/'; then
        yb_executable_process="odyssey"
    else
        yb_executable_process="postgres"
    fi
elif echo "$core_generated_line" | grep -qiE '(yb-controller-server|/bin/yb-controller-server)'; then
    yb_executable_process="yb-controller-server"
fi

# If we still don't have a process type, try to extract from full path (if available)
if [ -z "$yb_executable_process" ]; then
    # Try to extract full path for process identification (optional - only if needed)
    yb_executable_path_for_version=$(echo "$core_generated_line" | sed -n "s/.*Core was generated by \`\([^ '\"]*\).*/\1/p" | awk '{print $1}')

    # If that failed, try alternative extraction methods
    if [ -z "$yb_executable_path_for_version" ] || [[ ! "$yb_executable_path_for_version" =~ ^/ ]]; then
        # Try readelf as fallback
        if command -v readelf >/dev/null 2>&1; then
            readelf_notes=$(readelf -n "$file_name" 2>/dev/null)
            if [ -n "$readelf_notes" ]; then
                yb_executable_path_for_version=$(echo "$readelf_notes" | grep -oE '/[^[:space:]]*/(bin|postgres/bin)/(yb-tserver|yb-master|odyssey|postgres|yb-controller-server)[^[:space:]]*' | head -n 1)
            fi
        fi
    fi

    # If we got a path, identify process from it
    if [ -n "$yb_executable_path_for_version" ] && [[ "$yb_executable_path_for_version" =~ ^/ ]]; then
        if [[ "$yb_executable_path_for_version" == *"/bin/odyssey" ]] || [[ "$yb_executable_path_for_version" == *"/odyssey" ]]; then
            yb_executable_process="odyssey"
        elif [[ "$yb_executable_path_for_version" == *"/postgres/bin/postgres" ]]; then
            yb_executable_process="postgres"
        elif [[ "$yb_executable_path_for_version" == *"/bin/yb-tserver" ]] || [[ "$yb_executable_path_for_version" == *"/yb-tserver" ]]; then
            yb_executable_process="yb-tserver"
        elif [[ "$yb_executable_path_for_version" == *"/bin/yb-master" ]] || [[ "$yb_executable_path_for_version" == *"/yb-master" ]]; then
            yb_executable_process="yb-master"
        elif [[ "$yb_executable_path_for_version" == *"/bin/yb-controller-server" ]] || [[ "$yb_executable_path_for_version" == *"/yb-controller-server" ]]; then
            yb_executable_process="yb-controller-server"
        elif [[ "$yb_executable_path_for_version" == *"/bin/postgres" ]] && [[ "$yb_executable_path_for_version" != *"/postgres/"* ]]; then
            yb_executable_process="odyssey"
        elif [[ "$yb_executable_path_for_version" == *"/postgres/bin/"* ]]; then
            yb_executable_process="postgres"
        fi
    fi
fi

# If we still don't have a process type, we cannot proceed
if [ -z "$yb_executable_process" ]; then
    error_exit "Could not identify process type from GDB output: $core_generated_line"
fi

echo "✅ Process identified: $yb_executable_process"

# SECONDARY GOAL: Extract version using all possible methods (in order of speed)
# We only need the version pattern (e.g., 2025.1.1.2-b3), not the full path
# Methods tried in order: GDB -> readelf -n -> readelf -l -> file -> strings (chunked, only if needed)

echo "🔍 Extracting YugabyteDB version from core dump..."
yb_db_numeric_version=""

# Method 1: Extract version from GDB output (fastest, already have this)
if [ -z "$yb_db_numeric_version" ]; then
    # Extract version pattern from the core_generated_line
    yb_db_numeric_version=$(echo "$core_generated_line" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+' | head -n 1)
    [ -n "$yb_db_numeric_version" ] && echo "   ✓ Found version via GDB output"
fi

# Method 2: Try readelf -n (ELF notes, shows NT_FILE with mapped files)
# Pipe directly to grep to extract version pattern only
if [ -z "$yb_db_numeric_version" ]; then
    if command -v readelf >/dev/null 2>&1; then
        yb_db_numeric_version=$(readelf -n "$file_name" 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+' | head -n 1)
        [ -n "$yb_db_numeric_version" ] && echo "   ✓ Found version via readelf notes"
    fi
fi

# Method 3: Try readelf -l (program headers)
if [ -z "$yb_db_numeric_version" ]; then
    if command -v readelf >/dev/null 2>&1; then
        yb_db_numeric_version=$(readelf -l "$file_name" 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+' | head -n 1)
        [ -n "$yb_db_numeric_version" ] && echo "   ✓ Found version via readelf headers"
    fi
fi

# Method 4: Try 'file' command execfn
if [ -z "$yb_db_numeric_version" ]; then
    file_output=$(file "$file_name" 2>/dev/null)
    if echo "$file_output" | grep -q "execfn:"; then
        yb_db_numeric_version=$(echo "$file_output" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+' | head -n 1)
        [ -n "$yb_db_numeric_version" ] && echo "   ✓ Found version via file command"
    fi
fi

# Method 5: Use strings in chunks (like V3) - ONLY if other methods failed
# This is efficient: reads first 5GB in chunks (100M * 50) and stops at first match
if [ -z "$yb_db_numeric_version" ]; then
    if command -v strings >/dev/null 2>&1 && command -v dd >/dev/null 2>&1; then
        echo "   ⏳ Trying chunked strings method (this may take a moment)..."
        # Use efficient chunked approach: 100M chunks, 50 chunks = 5GB total (faster than 500M chunks)
        chunk_size="100M"
        chunk_count=50
        tempfile=$(mktemp)
        (dd if="$file_name" bs=$chunk_size count=$chunk_count 2>/dev/null | strings > "$tempfile") &
        dd_pid=$!
        blinkdots $dd_pid
        wait $dd_pid

        # Extract version pattern from the chunked output
        yb_db_numeric_version=$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+' "$tempfile" | head -n 1)
        rm -f "$tempfile"
        [ -n "$yb_db_numeric_version" ] && echo "   ✓ Found version via chunked strings"
    fi
fi

# Show final result
if [ -n "$yb_db_numeric_version" ]; then
    echo "✅ Version detected: $yb_db_numeric_version"
else
    echo "⚠️  Could not automatically detect version"
fi


# Check for yb-controller relates core file, if so exit right away. As YBC core file not supported by this script due to the YBC pck not available publicly to download etc.
if [[ "$yb_executable_process" == "yb-controller"* ]]; then
    echo "The YB-Controller related core file's analysis is not supported. You can reach out to agangwar@yugabyte.com to see if there is any alternate way. Thanks for your understanding."
    exit 1
fi

# Extract the OS architecture information
echo "🔍 Detecting OS architecture..."
os_architecture=""

if file "$file_name" | grep -q -E "x86-64|x86_64"; then
    os_architecture="x86_64"
elif file "$file_name" | grep -q "aarch64"; then
    os_architecture="aarch64"
else
    # Try to extract architecture from the path
    os_architecture_from_path=$(echo "$yb_executable_path_for_version" | grep -oE '(x86-64|x86_64|aarch64)')

    if [ -n "$os_architecture_from_path" ]; then
        # Replace "x86-64" with "x86_64"
        os_architecture="${os_architecture_from_path//-/_}"
    else
        os_architecture="unsupported"
    fi
fi

echo "🔸 OS architecture: $os_architecture"

# Separator
print_separator

# The full YB DB version by which the core file was created. If yb_db_numeric_version is not provided, prompt the user.
if [ -z "$yb_db_numeric_version" ]; then
    echo "⚠️  Could not automatically detect version. Manual input required."
    while true; do
        read -p "Please enter the executable version in the <MAJOR.MINOR.PATCH.REVISION-BUILDNumber> format (e.g., 2.18.1.0-b84): " yb_db_numeric_version
        if [[ ! $yb_db_numeric_version =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+$ ]]; then
            echo "❌ Invalid version format. Please enter in the format <MAJOR.MINOR.PATCH.REVISION-BUILDNumber>, for example, 2.18.1.0-b84"
        else
            break
        fi
    done
fi

# Extract version without build number for directory name (e.g., 2025.1.1.2-b3 -> 2025.1.1.2)
yb_db_numeric_version_without_build=$(echo "$yb_db_numeric_version" | sed 's/-b[0-9]\+$//')

# Construct tar file name for S3 bucket
# S3 bucket uses: almalinux8-aarch64 and centos-x86_64
if [ "$os_architecture" = "x86_64" ]; then
    yb_db_tar_file="yugabyte-$yb_db_numeric_version-centos-x86_64.tar.gz"
else
    yb_db_tar_file="yugabyte-$yb_db_numeric_version-almalinux8-aarch64.tar.gz"
fi

yb_db_install_dir="/home/yugabyte/yb-software"

# Check if the file already exists
if [ -f "$yb_db_install_dir/$yb_db_tar_file" ]; then
    echo "🔸 The file $yb_db_tar_file already exists in $yb_db_install_dir. Skipping the download step."
else
    echo "📥 Downloading the YB version file to $yb_db_install_dir/$yb_db_tar_file"
    # Download from S3 internal bucket
    # The Bucket is here: https://us-west-2.console.aws.amazon.com/s3/buckets/releases.yugabyte.com?region=us-west-2&bucketType=general&tab=objects
    yb_db_tar_s3_url="https://s3.us-west-2.amazonaws.com/releases.yugabyte.com/$yb_db_numeric_version/$yb_db_tar_file"
    response_code=$(curl -L --head -s -w "%{http_code}" "$yb_db_tar_s3_url" -o /dev/null)
    if [ "$response_code" -eq 200 ]; then
        # Note: curl -# shows progress bar, so we don't use blinkdots here
        curl -L -# "$yb_db_tar_s3_url" -o "$yb_db_install_dir/$yb_db_tar_file"
        if [ $? -eq 0 ]; then
            echo ""
            echo "✅ Download of YB version file succeeded from the internal S3 Release bucket."
        else
            error_exit "Download of YB version file from the internal S3 Release bucket failed."
        fi
    else
        error_exit "The YB version file does not exist at $yb_db_tar_s3_url."
    fi
fi

# Separator
print_separator

# Extract the yb binary tar file in the "/home/yugabyte/yb-software" dir
# BEST APPROACH: Discover the actual directory name from the tar file contents
# This is more robust than assuming the directory name matches the tar filename

# First, try to find an existing directory matching the version pattern
yb_db_executable_dir=$(find "$yb_db_install_dir" -maxdepth 1 -type d -name "yugabyte-${yb_db_numeric_version_without_build}*" 2>/dev/null | head -n 1)

if [ -n "$yb_db_executable_dir" ] && [ -d "$yb_db_executable_dir" ]; then
  echo "🔸 Found existing directory: $yb_db_executable_dir, not extracting again."
else
  # Discover the actual top-level directory name from the tar file
  echo "🔍 Discovering directory structure from $yb_db_tar_file..."
  top_level_dir=$(tar -tzf "$yb_db_install_dir/$yb_db_tar_file" 2>/dev/null | head -n 1 | cut -d'/' -f1)

  if [ -z "$top_level_dir" ]; then
    error_exit " Could not determine directory structure from $yb_db_tar_file. The tar file may be corrupted."
  fi

  yb_db_executable_dir="$yb_db_install_dir/$top_level_dir"

  # Check if this directory already exists (maybe from a previous extraction)
  if [ -d "$yb_db_executable_dir" ]; then
    echo "🔸 Directory $yb_db_executable_dir already exists, not extracting again."
  else
    echo "📦 Extracting $yb_db_tar_file in $yb_db_install_dir"
    tar -xzf "$yb_db_install_dir/$yb_db_tar_file" -C $yb_db_install_dir &>/dev/null &
    blinkdots $!
    if [ $? -eq 0 ]; then
      echo "✅ Extracting $yb_db_tar_file completed."
      # Verify the directory was created
      if [ ! -d "$yb_db_executable_dir" ]; then
        error_exit "Expected directory $yb_db_executable_dir not found after extraction. Please verify the tar file structure."
      fi
      echo "🔸 Extracted to: $yb_db_executable_dir"
    else
      error_exit "Failed to extract $yb_db_tar_file."
    fi
  fi
fi

# Separator
print_separator

# Execute post install script. This will setup the yb-db executable files to work with core and other cluster related stuff.

post_install="$yb_db_executable_dir/bin/post_install.sh"

if [ -f "$post_install" ]; then
  echo "🧬 Executing post_install script to setup the binary as per core dump..."
  $post_install &>/dev/null &
  blinkdots $!
  if [ $? -eq 0 ]; then
    echo "✅ Post-installation setup completed."
  else
    error_exit "Failed to execute post_install script."
  fi
else
  error_exit "$post_install not found."
fi

# Find the executable binary in the downloaded software directory using 'find'
# This is more robust than constructing the path manually, as it handles any directory structure
# IMPORTANT: For postgres, we must search for "postgres/bin/postgres" to avoid matching directories/symlinks
# For other processes, search in "bin/" directory to find the actual executable
echo "🔍 Searching for $yb_executable_process binary in $yb_db_executable_dir..."

if [[ "$yb_executable_process" == "postgres" ]]; then
    # For postgres, search specifically for postgres/bin/postgres to avoid matching:
    # - /home/yugabyte/master/postgres (symlink)
    # - /home/yugabyte/tserver/postgres (symlink)
    # - /home/yugabyte/yb-software/.../postgres (directory)
    # - /home/yugabyte/yb-software/.../lib/postgres (directory)
    # Note: Include both files (-type f) and symlinks (-type l) as yb-tserver/yb-master are symlinks
    yb_executable_relative_path=$(find "$yb_db_executable_dir" -path "*/postgres/bin/postgres" \( -type f -o -type l \) 2>/dev/null | head -n 1)
else
    # For other processes (yb-tserver, yb-master, odyssey), search in bin/ directory
    # Note: yb-tserver and yb-master are symlinks to yb-server, so we need to include symlinks
    # This ensures we find the actual executable or symlink, not libraries or other files
    yb_executable_relative_path=$(find "$yb_db_executable_dir" -path "*/bin/$yb_executable_process" \( -type f -o -type l \) 2>/dev/null | head -n 1)
fi

if [ -z "$yb_executable_relative_path" ]; then
    error_exit " Could not find $yb_executable_process binary in $yb_db_executable_dir. Please verify the software was extracted correctly."
fi

# Check if the path exists (works for both files and symlinks) and is executable
if [ ! -e "$yb_executable_relative_path" ]; then
    error_exit " Found binary path '$yb_executable_relative_path' but it does not exist."
fi

if [ ! -x "$yb_executable_relative_path" ]; then
    error_exit " Found binary path '$yb_executable_relative_path' but it is not executable."
fi

echo "✅ Found executable: $yb_executable_relative_path"

# Use the lldb command with the new input string
# Ask user to enetr available lldb command option for ease.
#The below section is to ask few more user inputs and redirection etc.

# Separator
print_separator

echo "👇 Select an option for lldb command and press ENTER:"
echo "1. bt"
echo "2. thread backtrace all"
echo "3. Other lldb command"
echo "4. Quit"
read -r option

while [[ ! "$option" =~ ^(1|2|3|4)$ ]]; do
  echo "❌ Invalid option selected. Please select either 1, 2, 3 or 4."
  echo "👇 Select an option for lldb command and press ENTER:"
  echo "1. bt"
  echo "2. thread backtrace all"
  echo "3. Other lldb command"
  echo "4. Quit"
  read -r option
done

# Separator
print_separator


if [ "$option" == "1" ]; then
  lldb_command="bt"
elif [ "$option" == "2" ]; then
  lldb_command="thread backtrace all"
elif [ "$option" == "3" ]; then
  echo "Enter the lldb command:"
  read -r lldb_command
fi

if [ "$option" != "4" ]; then
  echo "🗒️ Do you want to redirect the output to a file? (y/n)"
  read -r redirect_output
  while [[ ! "$redirect_output" =~ ^(y|n)$ ]]; do
    echo "❌ Invalid option selected. Please enter either y or n."
    echo "🗒️ Do you want to redirect the output to a file? (y/n)"
    read -r redirect_output
  done

# Separator
print_separator


if [ "$redirect_output" == "y" ]; then
  output_file="${file_name}_$(echo "$lldb_command" | tr -s ' ' '_')_analysis.out"
  echo "Output will be saved to $output_file"
  lldb --one-line-before-file "settings append target.exec-search-paths $(find $yb_db_executable_dir -type d | xargs echo)" -f "$yb_executable_relative_path" -c "$file_name" -o "$lldb_command" -o "quit" > "$output_file"
  echo "Analysis complete, the file '$output_file' has been saved."
else
  # Keep lldb in interactive mode (like V3) - don't add quit command
  # User can type "quit" in lldb to exit and return to shell
  lldb --one-line-before-file "settings append target.exec-search-paths $(find $yb_db_executable_dir -type d | xargs echo)" -f "$yb_executable_relative_path" -c "$file_name" -o "$lldb_command"
fi
fi
echo "Exiting."
exit 0
